INSERT INTO "loinc_local_code_map_part" ("id", "ref_loc_master_id", "loinc_code", "loinc_version", "active_flag", "create_user_id", "create_tstamp", "modify_user_id", "modify_tstamp", "device_map_flag", "loinc_component_description", "snomed_ct") VALUES
('228', '221',  '59032-3',  '2.63', 'Y',    NULL,   NULL,   NULL,   NULL,   NULL,   NULL,   '390996000 | Plasma lactate level (procedure) |'),
('231', '224',  '67511-6',  '2.63', 'Y',    NULL,   NULL,   NULL,   NULL,   NULL,   NULL,   '386329003 | Hypothermia treatment (procedure) |'),
('232', '225',  '20124-4',  '2.63', 'Y',    NULL,   NULL,   NULL,   NULL,   NULL,   NULL,   NULL),
('233', '226',  '38230-9',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '5540006'),
('234', '227',  '21377-7',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '72717003'),
('235', '228',  '2774-8',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '30820000'),
('236', '229',  '6299-2',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '72341003'),
('237', '230',  '38483-4',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '14804005'),
('247', '231',  '2339-0',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '67079006'),
('248', '232',  '49551-5',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '12016004'),
('249', '233',  '48425-3',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '102682001'),
('250', '234',  '42719-5',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '359986008'),
('251', '235',  '35672-5',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '54462003'),
('252', '236',  '1920-8',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '26091008'),
('253', '237',  '76625-3',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '56935002'),
('254', '238',  '1783-0',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '57056007'),
('255', '239',  '2324-2',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '60153001'),
('256', '240',  '42929-0',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '259319003'),
('257', '241',  '76630-3',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '387031005'),
('258', '242',  '3040-3',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '72993008'),
('259', '243',  '2885-2',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '304383000'),
('260', '244',  '1751-7',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '52454007'),
('261', '245',  '74433-4',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '412808005'),
('262', '246',  '2085-9',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '9422000'),
('263', '247',  '2089-1',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '22244007'),
('264', '248',  '2091-7',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '56516007'),
('265', '249',  '3043-7',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '85600001'),
('266', '250',  '789-8',    '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '258903009'),
('267', '251',  '20570-8',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '28317006'),
('268', '252',  '14196-0',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '45995003'),
('269', '253',  '26464-8',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '767002'),
('270', '254',  '26499-4',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '702967003'),
('271', '255',  '26474-7',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '56972008'),
('272', '256',  '26484-6',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '55918008'),
('273', '257',  '26449-9',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '14793004'),
('274', '258',  '26444-0',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '30061004'),
('275', '259',  '26515-7',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '277200003'),
('276', '260',  '30341-2',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '416560009'),
('277', '261',  '5894-1',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '396451008'),
('278', '262',  '3173-2',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '42525009'),
('279', '263',  '34714-6',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '165581004'),
('280', '264',  '30009-5',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '23295004'),
('281', '265',  '29263-1',  '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '89086000'),
('282', '266',  '2157-6',   '2.63', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL,   NULL,   '75828004');


INSERT INTO "local_code_group" ("id", "local_code", "local_description", "active_flag", "create_user_id", "create_tstamp", "modify_user_id", "modify_tstamp", "local_code_parent_id") VALUES
('228', 'gluco_meter_phosphorus',   'Phosphorus (2.7-4.5 mg/dl)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('227', 'gluco_meter_magnesium',    'Magnesium (0.6-1.1 nM/L)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('226', 'gluco_meter_calcium',  'Calcium (8.5-10.5 mg/dl)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('229', 'gluco_meter_bun',  'BUN (6-20 mg/dl)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('233', 'gluco_meter_trop', 'Trop. T',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('231', 'gluco_meter_glucose',  'Glucose (70-110 mg/dl)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('230', 'gluco_meter_creatintine',  'Creatintine (0.6-1.4 mg/dl)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('234', 'gluco_meter_totalbilirubin',   'Total bilirubin (< 1 mg/dl)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('242', 'gluco_meter_lipase',   'Lipase',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('245', 'gluco_meter_totalcholesterol', 'Total Cholesterol',    'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('246', 'gluco_meter_hdl',  'HDL',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('247', 'gluco_meter_ldl',  'LDL',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('248', 'gluco_meter_vldl', 'VLDL', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('249', 'gluco_meter_triglycerides',    'Tri Glycerides',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('259', 'gluco_meter_platelets',    'Platelets (ul)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('261', 'gluco_meter_prothrombintime',  'Prothrombin Time', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('262', 'gluco_meter_aptt', 'APTT', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('263', 'gluco_meter_inr',  'INR',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('264', 'gluco_meter_fibrinogen',   'Fibrinogen',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('265', 'gluco_meter_fdp',  'FDP',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('266', 'gluco_meter_creatinekinase',   'Creatine Kinase (CK) (26-174 U/L)',    'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('232', 'gluco_meter_ckmb', 'CK - MB (<\6% of Total CK)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('235', 'gluco_meter_directbilirubin',  'Direct bilirubin (< 0.4 mg/dl)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('236', 'gluco_meter_sgot', 'SGOT (AST) (< 0-40 U/L)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('237', 'gluco_meter_sgpt', 'SGPT (ALT) (U/L)SGPT (AST) (< 0-40 U/L)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('238', 'gluco_meter_alkalinephosphatase',  'Alkaline Phosphatase (30-115 U/L)',    'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('239', 'gluco_meter_gamagtp',  'Gama GTP (F5-55, M15-85 U/L)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('240', 'gluco_meter_ldh',  'LDH (90-220 U/L)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('241', 'gluco_meter_amylase',  'Amylase (31-123 U/L)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('243', 'gluco_meter_totalprotein', 'Total Protein (6-8.4 gm/dl)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('244', 'gluco_meter_albumin',  'Albumin (3.5-5.3 gm/dl)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('250', 'gluco_meter_rbc',  'RBC (3.5-5.5 106/ul)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('251', 'gluco_meter_haematocrit',  'Haematocrit (PCV) (35-55)',    'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('252', 'gluco_meter_reticulocytecount',    'Reticulocyte count (0.5-1.5 %)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('253', 'gluco_meter_wbc',  'WBC : Total Count (4.000-11.0000/ul)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('254', 'gluco_meter_dc',   'DC : Poly (40-75 %)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('255', 'gluco_meter_lymph',    'Lymph (0-75 %)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('256', 'gluco_meter_mono', 'Mono (2-10 %)',    'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('257', 'gluco_meter_eos',  'Eos (1-6 %)',  'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('258', 'gluco_meter_baso', 'Baso (0-1 %)', 'Y',    'NULL', NULL,   'NULL', NULL,   NULL),
('260', 'gluco_meter_esr',  'ESR (M: 3-10; F: 5-20)',   'Y',    'NULL', NULL,   'NULL', NULL,   NULL);

UPDATE config_settings
SET code_values = '["type_of_feeds",
"rectal_temp",
"type_of_care",
"warmer",
"work_of_breathing",
"core_temp",
"peripheral_temp",
"hr_rate",
"respiratory_rate",
"bp_method",
"cuff_systalic_bp",
"cuff_diastolic_bp",
"cuff_mean_bp",
"arterial_systalic_bp",
"arterial_diastolic_bp",
"arterial_mean_bp",
"preductal_sao2",
"postductal_sao2",
"color",
"mode_of_ventilation",
"p_amplitude",
"pip_set",
"pip_delivered",
"peep",
"map",
"fio2",
"flow",
"rate",
"it_rate",
"frequency",
"it_rate_secound",
"ie_r",
"cpap_interface_change",
"humidifier_temp",
"physiotherapy",
"suction",
"route_of_feeds",
"respiratory_rate",
"urine_output",
"bowels",
"gastric_aspirate_volume",
"gastric_aspirate",
"drain_output_r",
"drain_output_l",
"drains_ml",
"blood_volume_out",
"et_size",
"incubator",
"blood_sugar",
"current_weight",
"working_weight",
"activity",
"targeted_tidal_volume",
"delivered_tidal_volume",
"human_milk_fortification",
"milk_volume",
"Transfusion",
"stools_nature",
"intravenous_fluids",
"oral_fluids",
"other_drugs",
"total_intake_ml",
"total_intake_kg",
"aspirate_ml",
"urine_total",
"urine_total_ml_kg",
"blood_out_total",
"stools_frequency",
"stoma_output",
"i_o_balance",
"i_o_balance_ml_kg",
"air_entry_right",
"air_entry_left",
"volume_targeting",
"hhhfnc",
"physiotherapy",
"suction",
"human_milk_fortification",
"kmc",
"nns",
"bowels",
"position",
"et_length",
"ngt_size",
"ngt_length",
"milk_feeds",
"milk_volume_total",
"stoma_output_hour_total",
"stoma_output_hour",
"blood_gas_type",
"last_bg_time",
"blood_gas_ph",
"blood_gas_pao2",
"blood_gas_paco2",
"blood_gas_hco3",
"blood_gas_be",
"blood_gas_na",
"blood_gas_k",
"blood_gas_cl",
"blood_gas_hb",
"blood_gas_pcv",
"blood_gas_lactate",
"blood_gas_bilirubin",
"blood_gas_methemoglobin",
"therapeutic_hypothermia",
"gastric_aspirate_volume_total",
"urine_output_total",
"blood_volume_out_total",
"drain_output_r_total",
"drain_output_l_total",
"mode_of_ventilation_invasive",
"gluco_meter_calcium",
"gluco_meter_magnesium",
"gluco_meter_phosphorus",
"gluco_meter_bun",
"gluco_meter_creatintine",
"gluco_meter_glucose",
"gluco_meter_creatinekinase",
"gluco_meter_ckmb",
"gluco_meter_trop",
"gluco_meter_totalbilirubin",
"gluco_meter_directbilirubin",
"gluco_meter_sgot",
"gluco_meter_sgpt",
"gluco_meter_alkalinephosphatase",
"gluco_meter_gamagtp",
"gluco_meter_ldh",
"gluco_meter_amylase",
"gluco_meter_lipase",
"gluco_meter_totalprotein",
"gluco_meter_albumin",
"gluco_meter_totalcholesterol",
"gluco_meter_hdl",
"gluco_meter_ldl",
"gluco_meter_vldl",
"gluco_meter_triglycerides",
"gluco_meter_rbc",
"gluco_meter_haematocrit",
"gluco_meter_reticulocytecount",
"gluco_meter_wbc",
"gluco_meter_dc",
"gluco_meter_lymph",
"gluco_meter_mono",
"gluco_meter_eos",
"gluco_meter_baso",
"gluco_meter_platelets",
"gluco_meter_esr",
"gluco_meter_prothrombintime",
"gluco_meter_aptt",
"gluco_meter_inr",
"gluco_meter_fibrinogen",
"gluco_meter_fdp"
]';

-- Adminer 4.3.1 PostgreSQL dump

DROP TABLE IF EXISTS "lab_temporary_data";

CREATE TABLE "public"."lab_temporary_data" (
    "resourceType" text,
    "id" text,
    "identifier" text,
    "status" text,
    "code" text,
    "subject" text,
    "effectivePeriod" text,
    "issued" text,
    "performer" text,
    "valueQuantity" text,
    "interpretation" text,
    "referenceRange" text,
    "Id" bigint DEFAULT nextval('"lab_temporary_data_Id_seq"') NOT NULL,
    "text" text
) WITH (oids = false);


-- 2019-12-11 16:26:48.31627+05:30
