	    <th class="fixed-columns-width">Baby Name</th> 
        <th class="fixed-columns-width">Baby {{ Lang::get('home.mrn') }}</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['DOB'] }}">DOB</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['DayOfLife'] }}">Day Of Life</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['cg_weeks'] }}">Corrected Gestational Age Weeks</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['cg_days'] }}">Corrected Gestational Age Days</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Care'] }}">Care</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Sex'] }}">Sex</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['DayDate'] }}">Date of Record</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['DayTime'] }}">Time of Record</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['CurrentProblems'] }}">Current Problems</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['PreviousProblems'] }}">Previous Problems</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['Background'] }}">Background</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['ResICD'] }}">Respiratory ICD</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['InvasiveVentilation'] }}">Invasive Ventilation</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Ventilation_choose'] }}">Ventilation Choose</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ModeOfVentilation'] }}">Invasive Ventilation Type</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['NonInvasiveVentilation'] }}">Non-Invasive Ventilation</th>
		<th class="flex-filter {{ $daycareHeadclass['OtherRespiratorySupport'] }}">Other Respiratory Support</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Spontaneouslyventilating'] }}">Spontaneously Ventilating</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PIP'] }}">PIP</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PEEP'] }}">PEEP</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['MAP'] }}">MAP</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['FiO2'] }}">FiO2</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Rate'] }}">Ventilator Rate</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['frequency_rep'] }}">Frequency (Hz)</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['IT'] }}">IT in sec</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['Flow'] }}">Flow (L/min)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Indication'] }}">Respiratory Indication</th>
		<th class="flex-filter flex-width-large   {{ $daycareHeadclass['Surfactant_therapy_nicu'] }}">Surfactant Therapy in the NICU</th>
		<th class="flex-filter flex-width-large   {{ $daycareHeadclass['surfactant_indication'] }}">Indication For Surfactant</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['RR'] }}">Baby's Respiratory Rate</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Retractions'] }}">Retractions</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['AirEntry'] }}">Air entry</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ChestMovement'] }}">Chest Movement</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['AddedSounds'] }}">Added Sounds</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['DayCharacter'] }}">Character</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['CXRFindings'] }}">CXR Findings</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['TypeOfBloodGas'] }}">Type Of Blood Gas</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['LastBG'] }}">Last BG at </th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['Ph'] }}">PH</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['PaO2'] }}">PaO2</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['PaCo2'] }}">PaCo2</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['HCO3'] }}">HCO3</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['BE'] }}">BE</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Lactate'] }}">Lactate</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['EtTube'] }}">Et Tube</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Size'] }}">Size in cm</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Lips'] }}">Cm at Lips</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['SaO2PostDuctal'] }}">SaO2 PostDuctal</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['AaDO2'] }}">AaDO2</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['OI'] }}">OI</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['RSFindings'] }}">Other RS Findings</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['needlethoracentesis'] }}">Needle Thoracocentesis</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['intercostaldrain'] }}">Intercostal Drain</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['chronic_lung'] }}">Chronic Lung Disease</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CarICD'] }}">Cardiovascular ICD</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['HR'] }}">HR</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['systolic_bp'] }}">Systolic BP</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['diastolic_bp'] }}">Diastolic BP</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['MeanBP'] }}">Mean BP</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PulsePressure'] }}">Pulse Pressure</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CentralPulses'] }}">Central Pulses</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralPulses'] }}">Peripheral Pulses</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['FemoralPulses'] }}">Femoral Pulses</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PrecordialActivity'] }}">Precordial Activity</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['S1S2'] }}">S1S2</th> 
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Murmur'] }}">Murmur</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CharacterOfMurmur'] }}">Character Of Murmur</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CVSFindings'] }}">Other CVS Findings</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['CFT'] }}">CFT</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CentralTemperature'] }}">Central Temperature</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralTemperature'] }}">Peripheral Temperature</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Color'] }}">Color</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Inotropes'] }}">Inotropes</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Dopamine'] }}">Dopamine (mcg/kg/min)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Dobutamine'] }}">Dobutamine (mcg/kg/min)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Adrenaline'] }}">Adrenaline (ng/kg/min)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Noradrenaline'] }}">Nor adrenaline (ng/kg/min)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Milrinone'] }}">Milrinone (mcg/kg/hour)</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['DayEcho'] }}">Echo</th>
		<th class="flex-filter {{ $daycareHeadclass['echo_status'] }}">ECHO Report</th>
		<th class="flex-filter flex-width-small  {{ $daycareHeadclass['PDA'] }}">PDA</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['PDATreatment'] }}">PDA Treatment</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['pphn'] }}">PPHN</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['pphn_treatement'] }}">PPHN Treatement</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['GasICD'] }}">Gastrointestinal ICD</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['directlybreastfeed'] }}">Directly breast feed</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['othertypefeed'] }}">Other Type Of Feeds</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Volume'] }}">Volume</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Frequency'] }}">Frequency</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['workingWeight'] }}">working Weight</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Feeds'] }}">Feeds ml/kg/d</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TypeofFeeds'] }}">Type of feeds</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['FullEnteralFeeds'] }}">Full Enteral Feeds</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['iv_fluids'] }}">IV fluids +/- PN ml/hour</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['iv_fluids_ml_day'] }}">IV fluids ml/day</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['drug_infusions'] }}">Drug Infusions ml/hour</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['drug_infusions_ml_day'] }}">Drug Infusions ml/day</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['other_drugs'] }}">Other Drugs ml/day</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Ivf'] }} ">IV fluids +/- PN ml/kg/d</th>
		<th class="flex-filter flex-width-small   {{ $daycareHeadclass['Tpn'] }}">TPN</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Carbohydrates'] }}">Carbohydrates (g/kg/day)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Protein'] }}">Amino Acid (g/kg/day)</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Fat'] }}">Fat (g/kg/day)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['total_energy'] }}">Total Energy (kcal/kg/day)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AspirateVolume'] }}">Aspirate Volume</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AspirateNature'] }}">AspirateNature</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Stools'] }}">Stools</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['StoolNature'] }}">Stool Nature</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Abdomen'] }}">Abdomen</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['BowelSounds'] }}">Bowel Sounds</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['AbdominalGirth'] }}">Abdominal Girth</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PAFindings'] }}">Other PA Findings</th>
		<th class="flex-filter flex-width-small   {{ $daycareHeadclass['NEC'] }}">NEC</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['NECtreatment'] }}">NEC treatment</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Umbilicus'] }}">Umbilicus</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hepatomegaly'] }}">Hepatomegaly</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['LiverSpan'] }}">Liver Span</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Splenomegaly'] }}">Splenomegaly</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['SpleenSpan'] }}">Spleen Span</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Herina'] }}">Hernia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Genitalia'] }}">Genitalia</th>
		<th class="flex-filter flex-width-large   {{ $daycareHeadclass['TSB'] }}">Maximum Bilirubin (in last 24 hours)</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['NNJTreatment'] }}">NNJ Treatment</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Immunoglobulins'] }}">Immunoglobulins</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['BabyBloodGroup'] }}">Baby Blood Group</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['MotherBloodGroup'] }}">Mother Blood Group</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['AxrFindings'] }}">AXR Findings</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ultrasoundabdominal'] }}">Ultrasound Abdominal</th>
		<th class="flex-filter {{ $daycareHeadclass['ultrasoundkeyfindings'] }}">Ultrasound key Findings</th>
		<th class="flex-filter {{ $daycareHeadclass['CenICD'] }}">Central Nervous ICD</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TherapeuticHypothermia'] }}">TherapeuticHypothermia</th>
		<th class="flex-filter flex-width-large   {{ $daycareHeadclass['Pupils'] }}">Pupils</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AnteriorFontanelle'] }}">Anterior Fontanelle</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Activity'] }}">Activity</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Tone'] }}">Tone</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Cry'] }}">Cry</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Seizures'] }}">Seizures</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TypeOfSeizures'] }}">Type Of Seizures</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['NeonatalReflexes'] }}">Neonatal Reflexes</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CnsFindings'] }}">Other CNS Findings</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['neuro_sonogram'] }}">Neuro Sonogram</th>
		<th class="flex-filter {{ $daycareHeadclass['Cuss'] }}">Neuro Sonogram Report</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ultrasound_spine'] }}">Ultrasound Spine</th>
		<th class="flex-filter {{ $daycareHeadclass['ultrasound_spine_report'] }}">Ultrasound Spine Report</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['mrict_brain_status'] }}">MRI/CT Brain</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['mri_ct_brain'] }}">MRI/CT Brain Key Findings</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['eeg_cfm'] }}">EEG/CFM</th>
		<th class="flex-filter {{ $daycareHeadclass['eeg_cfm_report'] }}">EEG/CFM Report</th>
		<th class="flex-filter {{ $daycareHeadclass['FluidICD'] }}">Fluid Balance ICD</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TotalFluid'] }}">Total Fluid ml/kg/d</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PreviousWt'] }}">Previous Weight</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['CurrentWt'] }}">Current Weight</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['WtChange'] }}">Weight Change</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PercentageChange'] }}">Percentage Change</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['UrineOutput'] }}">Urine Output</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['urine_output_day'] }}">UO ml (in 24 hours)</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['UO'] }}">UO ml/kg/h</th>
		<th class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['BloodOut'] }}">Blood Out</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['DrainOutput'] }}">Drain Output</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['renalultrasound'] }}">Renal Ultrasound</th>
		<th class="flex-filter flex-width-large {{ $daycareHeadclass['renalultrasoundkeyfindings'] }}">renal ultrasound key findings</th>
		<th class="flex-filter flex-width-xsmall {{ $daycareHeadclass['RBS'] }}">RBS</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hypoglycemia'] }}">Hypoglycemia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['gir'] }}">gir</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hyperglycemia'] }}">Hyperglycemia</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['InsulinTherapy'] }}">Insulin Therapy</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hyponatremia'] }}">Hyponatremia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hypernatremia'] }}">Hypernatremia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hypokalemia'] }}">Hypokalemia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hyperkalemia'] }}">Hyperkalemia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hypocalcemia'] }}">Hypocalcemia</th>
		<th class="flex-filter flex-width-medium {{ $daycareHeadclass['Hypercalcemia'] }}">Hypercalcemia</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['dilution_exchange'] }}">Dilution Exchange</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Transfusion'] }}">Transfusion</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['F_Product'] }}">Product</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['F_Volume'] }}">Volume ml/kg</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['SepsisICD'] }}">Sepsis ICD</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Sepsis'] }}">Sepsis</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['A_Antibiotic'] }}">Antibiotic</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['A_Day'] }}">Antibiotic Day</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['CRP'] }}">CRP mg per L</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['TLC'] }}">TLC per cu.mm</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Percentage'] }} ">Percentage N</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['ANC'] }}">ANC per cu.mm</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Platelets'] }}">Platelets per cu.mm</th>
		<th class="flex-filter flex-width-xlarge {{ $daycareHeadclass['OtherDrugs'] }}">OtherDrugs</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['BloodCulture'] }}">Blood Culture</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Organism'] }}">Organism</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PositiveBlood'] }}">Positive Blood Culture DOL</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['lumbar_puncture'] }}">Lumbar puncture</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Meningitis'] }}">Meningitis</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['viral_meningitis'] }}">Viral Meningitis/Encephalitis</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralCannula'] }}">Peripheral Cannula</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['pvc_number'] }}">PVC Number</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PvcComplication'] }}">PvcComplication</th>
		<th class="flex-filter flex-width-small   {{ $daycareHeadclass['Picc'] }}">Picc</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PiccSite'] }}">Picc Site</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PiccDay'] }}">Picc Day</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PiccComplication'] }}">Picc Complication</th>
		<th class="flex-filter flex-width-small {{ $daycareHeadclass['Uvc'] }}">Uvc</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcPosition'] }}">Uvc Position</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcDay'] }}">UvcDay</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcComplication'] }}">Uvc Complication</th>
		<th class="flex-filter flex-width-small   {{ $daycareHeadclass['Uac'] }}">Uac</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacPosition'] }}">Uac Position</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacDay'] }}">Uac Day</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacComplication'] }}">Uac Complication</th>
		<th class="flex-filter flex-width-small  {{ $daycareHeadclass['Pac'] }}">PAC</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PacSite'] }}">Pac Site</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['PacDay'] }}">Pac Day</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PacComplication'] }}">Pac Complication</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['SkinICD'] }}">Skin ICD</th>
		<th class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Skin'] }}">Skin</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['RopICD'] }}">Rop ICD</th>
		<th class="flex-filter flex-width-medium  {{ $daycareHeadclass['Rop'] }}">Rop</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['Plan'] }}">Plan</th>
		<th class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['Notes'] }}">Notes</th>








