@foreach($daycareList as $daycareRecord)  
                   <tr>     
                        <td class="fixed-columns-width"> {!! $daycareRecord->BabyName !!} </td>                                    
                        <td class="fixed-columns-width"> {!! $daycareRecord->baby_mrno !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['DOB'] }}"> {!! date('d-m-Y', strtotime($daycareRecord->DOB)) !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['DayOfLife'] }}"> {!! $daycareRecord->DayOfLife !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['cg_weeks'] }}"> {!! $daycareRecord->cg_weeks !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['cg_days'] }}"> {!! $daycareRecord->cg_days !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Care'] }}"> {!! $daycareRecord->Care !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Sex'] }}"> {!! $daycareRecord->Sex !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['DayDate'] }}"> {!! date('d-m-Y', strtotime($daycareRecord->DayDate)) !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['DayTime'] }}"> {!! $daycareRecord->DayTime !!} </td>
                        <td class="flex-filter flex-width-xlarge {{ $daycareHeadclass['CurrentProblems'] }}"> {!! $daycareRecord->CurrentProblems !!} </td>
                        <td class="flex-filter flex-width-xlarge {{ $daycareHeadclass['PreviousProblems'] }}"> {!! $daycareRecord->PreviousProblems !!} </td>
                        <td class="flex-filter flex-width-xlarge {{ $daycareHeadclass['Background'] }}"> {!! $daycareRecord->Background !!} </td>
                        <td class="flex-filter flex-width-xlarge  {{ $daycareHeadclass['ResICD'] }}"> {!! isset($daycareRecord->ResICD)? $daycareRecord->ResICD : '' !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['InvasiveVentilation'] }}"> {!! $daycareRecord->InvasiveVentilation !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Ventilation_choose'] }}"> {!! $daycareRecord->Ventilation_choose !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ModeOfVentilation'] }}"> {!! $daycareRecord->ModeOfVentilation !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['NonInvasiveVentilation'] }}"> {!! $daycareRecord->NonInvasiveVentilation !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['OtherRespiratorySupport'] }}"> {!! $daycareRecord->OtherRespiratorySupport !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Spontaneouslyventilating'] }}"> {!! $daycareRecord->Spontaneouslyventilating !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PIP'] }}"> {!! $daycareRecord->PIP !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PEEP'] }}"> {!! $daycareRecord->PEEP !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['MAP'] }}"> {!! $daycareRecord->MAP !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['FiO2'] }}"> {!! $daycareRecord->FiO2 !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Rate'] }}"> {!! $daycareRecord->Rate !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['frequency_rep'] }}"> {!! $daycareRecord->frequency_rep !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['IT'] }}"> {!! $daycareRecord->IT !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Flow'] }}"> {!! $daycareRecord->Flow !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Indication'] }}"> {!! $daycareRecord->Indication !!} </td>
                        <td class="flex-filter flex-width-large {{ $daycareHeadclass['Surfactant_therapy_nicu'] }}"> {!! $daycareRecord->Surfactant_therapy_nicu !!} </td>
                        <td class="flex-filter flex-width-large   {{ $daycareHeadclass['surfactant_indication'] }}"> {!! $daycareRecord->surfactant_indication !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['RR'] }}"> {!! $daycareRecord->RR !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Retractions'] }}"> {!! $daycareRecord->Retractions !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['AirEntry'] }}"> {!! $daycareRecord->AirEntry !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ChestMovement'] }}"> {!! $daycareRecord->ChestMovement !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['AddedSounds'] }}"> {!! $daycareRecord->AddedSounds !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['DayCharacter'] }}"> {!! $daycareRecord->DayCharacter !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['CXRFindings'] }}"> {!! $daycareRecord->CXRFindings !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['TypeOfBloodGas'] }}"> {!! $daycareRecord->TypeOfBloodGas !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['LastBG'] }}"> {!! $daycareRecord->LastBG !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['Ph'] }}"> {!! $daycareRecord->Ph !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PaO2'] }}"> {!! $daycareRecord->PaO2 !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['PaCo2'] }}"> {!! $daycareRecord->PaCo2 !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['HCO3'] }}"> {!! $daycareRecord->HCO3 !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['BE'] }}"> {!! $daycareRecord->BE !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Lactate'] }}"> {!! $daycareRecord->Lactate !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['EtTube'] }}"> {!! $daycareRecord->EtTube !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Size'] }}"> {!! $daycareRecord->Size !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['Lips'] }}"> {!! $daycareRecord->Lips !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['SaO2PostDuctal'] }}"> {!! $daycareRecord->SaO2PostDuctal !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['AaDO2'] }}"> {!! $daycareRecord->AaDO2 !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['OI'] }}"> {!! $daycareRecord->OI !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['RSFindings'] }}"> {!! $daycareRecord->RSFindings !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['needlethoracentesis'] }}"> {!! $daycareRecord->needlethoracentesis !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['intercostaldrain'] }}"> {!! $daycareRecord->intercostaldrain !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['chronic_lung'] }}"> {!! $daycareRecord->chronic_lung !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CarICD'] }}"> {!! isset($daycareRecord->CarICD) ? $daycareRecord->CarICD : '' !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['HR'] }}"> {!! $daycareRecord->HR !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['systolic_bp'] }}"> {!! $daycareRecord->systolic_bp !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['diastolic_bp'] }}"> {!! $daycareRecord->diastolic_bp !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['MeanBP'] }}"> {!! $daycareRecord->MeanBP !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PulsePressure'] }}"> {!! $daycareRecord->PulsePressure !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CentralPulses'] }}"> {!! $daycareRecord->CentralPulses !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralPulses'] }}"> {!! $daycareRecord->PeripheralPulses !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['FemoralPulses'] }}"> {!! $daycareRecord->FemoralPulses !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PrecordialActivity'] }}"> {!! $daycareRecord->PrecordialActivity !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['S1S2'] }}"> {!! $daycareRecord->S1S2 !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Murmur'] }}"> {!! $daycareRecord->Murmur !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CharacterOfMurmur'] }}"> {!! $daycareRecord->CharacterOfMurmur !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CVSFindings'] }}"> {!! $daycareRecord->CVSFindings !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['CFT'] }}"> {!! $daycareRecord->CFT !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CentralTemperature'] }}"> {!! $daycareRecord->CentralTemperature !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralTemperature'] }}"> {!! $daycareRecord->PeripheralTemperature !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Color'] }}"> {!! $daycareRecord->Color !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Inotropes'] }}"> {!! $daycareRecord->Inotropes !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Dopamine'] }}"> {!! $daycareRecord->Dopamine !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Dobutamine'] }}"> {!! $daycareRecord->Dobutamine !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Adrenaline'] }}"> {!! $daycareRecord->Adrenaline !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Noradrenaline'] }}"> {!! $daycareRecord->Noradrenaline !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Milrinone'] }}"> {!! $daycareRecord->Milrinone !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['echo_status'] }}"> {!! $daycareRecord->echo_status !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['DayEcho'] }}"> {!! $daycareRecord->DayEcho !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['PDA'] }}"> {!! $daycareRecord->PDA !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PDATreatment'] }}"> {!! $daycareRecord->PDATreatment !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['pphn'] }}"> {!! $daycareRecord->pphn !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['pphn_treatement'] }}"> {!! $daycareRecord->pphn_treatement !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['GasICD'] }}"> {!! isset($daycareRecord->GasICD) ? $daycareRecord->GasICD : '' !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['directlybreastfeed'] }}"> {!! $daycareRecord->directlybreastfeed !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['othertypefeed'] }}"> {!! $daycareRecord->othertypefeed !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Volume'] }}"> {!! $daycareRecord->Volume !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Frequency'] }}"> {!! $daycareRecord->Frequency !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['workingWeight'] }}"> {!! $daycareRecord->workingWeight !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Feeds'] }}"> {!! $daycareRecord->Feeds !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TypeofFeeds'] }}"> {!! $daycareRecord->TypeofFeeds !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['FullEnteralFeeds'] }}"> {!! $daycareRecord->FullEnteralFeeds !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['iv_fluids'] }}"> {!! $daycareRecord->iv_fluids !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['iv_fluids_ml_day'] }}"> {!! $daycareRecord->iv_fluids_ml_day !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['drug_infusions'] }}"> {!! $daycareRecord->drug_infusions !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['drug_infusions_ml_day'] }}"> {!! $daycareRecord->drug_infusions_ml_day !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['other_drugs'] }}"> {!! $daycareRecord->other_drugs !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['Ivf'] }}"> {!! $daycareRecord->Ivf !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['Tpn'] }}"> {!! $daycareRecord->Tpn !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Carbohydrates'] }}"> {!! $daycareRecord->Carbohydrates !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Protein'] }}"> {!! $daycareRecord->Protein !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Fat'] }}"> {!! $daycareRecord->Fat !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['total_energy'] }}"> {!! $daycareRecord->total_energy !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AspirateVolume'] }}"> {!! $daycareRecord->AspirateVolume !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AspirateNature'] }}"> {!! $daycareRecord->AspirateNature !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Stools'] }}"> {!! $daycareRecord->Stools !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['StoolNature'] }}"> {!! $daycareRecord->StoolNature !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Abdomen'] }}"> {!! $daycareRecord->Abdomen !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['BowelSounds'] }}"> {!! $daycareRecord->BowelSounds !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['AbdominalGirth'] }}"> {!! $daycareRecord->AbdominalGirth !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PAFindings'] }}"> {!! $daycareRecord->PAFindings !!} </td>
                        <td class="flex-filter flex-width-small   {{ $daycareHeadclass['NEC'] }}"> {!! $daycareRecord->NEC !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['NECtreatment'] }}"> {!! $daycareRecord->NECtreatment !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Umbilicus'] }}"> {!! $daycareRecord->Umbilicus !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hepatomegaly'] }}"> {!! $daycareRecord->Hepatomegaly !!} </td>
                        <td class="flex-filter flex-width-xsmall  {{ $daycareHeadclass['LiverSpan'] }}"> {!! $daycareRecord->LiverSpan !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Splenomegaly'] }}"> {!! $daycareRecord->Splenomegaly !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['SpleenSpan'] }}"> {!! $daycareRecord->SpleenSpan !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Herina'] }}"> {!! $daycareRecord->Herina !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Genitalia'] }}"> {!! $daycareRecord->Genitalia !!} </td>
                        <td class="flex-filter flex-width-large   {{ $daycareHeadclass['TSB'] }}"> {!! $daycareRecord->TSB !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['NNJTreatment'] }}"> {!! $daycareRecord->NNJTreatment !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Immunoglobulins'] }}"> {!! $daycareRecord->Immunoglobulins !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['BabyBloodGroup'] }}"> {!! $daycareRecord->BabyBloodGroup !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['MotherBloodGroup'] }}"> {!! $daycareRecord->MotherBloodGroup !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['AxrFindings'] }}"> {!! $daycareRecord->AxrFindings !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ultrasoundabdominal'] }}"> {!! $daycareRecord->ultrasoundabdominal !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['ultrasoundkeyfindings'] }}"> {!! $daycareRecord->ultrasoundkeyfindings !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['CenICD'] }}"> {!! isset($daycareRecord->CenICD) ? $daycareRecord->CenICD : '' !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TherapeuticHypothermia'] }}"> {!! $daycareRecord->TherapeuticHypothermia !!} </td>
                        <td class="flex-filter flex-width-large {{ $daycareHeadclass['Pupils'] }}"> {!! $daycareRecord->Pupils !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['AnteriorFontanelle'] }}"> {!! $daycareRecord->AnteriorFontanelle !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Activity'] }}"> {!! $daycareRecord->Activity !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Tone'] }}"> {!! $daycareRecord->Tone !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Cry'] }}"> {!! $daycareRecord->Cry !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Seizures'] }}"> {!! $daycareRecord->Seizures !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TypeOfSeizures'] }}"> {!! $daycareRecord->TypeOfSeizures !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['NeonatalReflexes'] }}"> {!! $daycareRecord->NeonatalReflexes !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['CnsFindings'] }}"> {!! $daycareRecord->CnsFindings !!} </td>
                        <td class="flex-filter flex-width-xmedium  {{ $daycareHeadclass['neuro_sonogram'] }}"> {!! $daycareRecord->neuro_sonogram !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['Cuss'] }}"> {!! $daycareRecord->Cuss !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['ultrasound_spine'] }}"> {!! $daycareRecord->ultrasound_spine !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['ultrasound_spine_report'] }}"> {!! $daycareRecord->ultrasound_spine_report !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['mrict_brain_status'] }}"> {!! $daycareRecord->mrict_brain_status !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['mri_ct_brain'] }}"> {!! $daycareRecord->mri_ct_brain !!} </td>
                        <td class="flex-filter  flex-width-xsmall {{ $daycareHeadclass['eeg_cfm'] }}"> {!! $daycareRecord->eeg_cfm !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['eeg_cfm_report'] }}"> {!! $daycareRecord->eeg_cfm_report !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['FluidICD'] }}"> {!! isset($daycareRecord->FluidICD) ? $daycareRecord->FluidICD : '' !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['TotalFluid'] }}"> {!! $daycareRecord->TotalFluid !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PreviousWt'] }}"> {!! $daycareRecord->PreviousWt !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['CurrentWt'] }}"> {!! $daycareRecord->CurrentWt !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['WtChange'] }}"> {!! $daycareRecord->WtChange !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PercentageChange'] }}"> {!! $daycareRecord->PercentageChange !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['UrineOutput'] }}"> {!! $daycareRecord->UrineOutput !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['urine_output_day'] }}"> {!! $daycareRecord->urine_output_day !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['UO'] }}"> {!! $daycareRecord->UO !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['BloodOut'] }}"> {!! $daycareRecord->BloodOut !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['DrainOutput'] }}"> {!! $daycareRecord->DrainOutput !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['renalultrasound'] }}"> {!! $daycareRecord->renalultrasound !!} </td>
                        <td class="flex-filter flex-width-large {{ $daycareHeadclass['renalultrasoundkeyfindings'] }}"> {!! $daycareRecord->renalultrasoundkeyfindings !!} </td>
                        <td class="flex-filter flex-width-xsmall {{ $daycareHeadclass['RBS'] }}"> {!! $daycareRecord->RBS !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hypoglycemia'] }}"> {!! $daycareRecord->Hypoglycemia !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['gir'] }}"> {!! $daycareRecord->gir !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hyperglycemia'] }}"> {!! $daycareRecord->Hyperglycemia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['InsulinTherapy'] }}"> {!! $daycareRecord->InsulinTherapy !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hyponatremia'] }}"> {!! $daycareRecord->Hyponatremia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hypernatremia'] }}"> {!! $daycareRecord->Hypernatremia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hypokalemia'] }}"> {!! $daycareRecord->Hypokalemia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hyperkalemia'] }}"> {!! $daycareRecord->Hyperkalemia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hypocalcemia'] }}"> {!! $daycareRecord->Hypocalcemia !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Hypercalcemia'] }}"> {!! $daycareRecord->Hypercalcemia !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['dilution_exchange'] }}"> {!! $daycareRecord->dilution_exchange !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Transfusion'] }}"> {!! $daycareRecord->Transfusion !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['F_Product'] }}"> {!! $daycareRecord->F_Product !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['F_Volume'] }}"> {!! $daycareRecord->F_Volume !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['SepsisICD'] }}"> {!! isset($daycareRecord->SepsisICD) ? $daycareRecord->SepsisICD : '' !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Sepsis'] }}"> {!! $daycareRecord->Sepsis !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['A_Antibiotic'] }}"> {!!$daycareRecord->A_Antibiotic !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['A_Day'] }}"> {!! $daycareRecord->A_Day !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['CRP'] }}"> {!! $daycareRecord->CRP !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['TLC'] }}"> {!! $daycareRecord->TLC !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Percentage'] }}"> {!! $daycareRecord->Percentage !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['ANC'] }}"> {!! $daycareRecord->ANC !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Platelets'] }}"> {!! $daycareRecord->Platelets !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['OtherDrugs'] }}"> {!! $daycareRecord->OtherDrugs !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['BloodCulture'] }}"> {!! $daycareRecord->BloodCulture !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Organism'] }}"> {!! $daycareRecord->Organism !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PositiveBlood'] }}"> {!! $daycareRecord->PositiveBlood !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['lumbar_puncture'] }}"> {!! $daycareRecord->lumbar_puncture !!} </td>
                        <td class="flex-filter flex-width-medium  {{ $daycareHeadclass['Meningitis'] }}"> {!! $daycareRecord->Meningitis !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['viral_meningitis'] }}"> {!! $daycareRecord->viral_meningitis !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PeripheralCannula'] }}"> {!! $daycareRecord->PeripheralCannula !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['pvc_number'] }}"> {!! $daycareRecord->pvc_number !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PvcComplication'] }}"> {!! $daycareRecord->PvcComplication !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['Picc'] }}"> {!! $daycareRecord->Picc !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PiccSite'] }}"> {!! $daycareRecord->PiccSite !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PiccDay'] }}"> {!! $daycareRecord->PiccDay !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PiccComplication'] }}"> {!! $daycareRecord->PiccComplication !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['Uvc'] }}"> {!! $daycareRecord->Uvc !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcPosition'] }}"> {!! $daycareRecord->UvcPosition !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcDay'] }}"> {!! $daycareRecord->UvcDay !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UvcComplication'] }}"> {!! $daycareRecord->UvcComplication !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['Uac'] }}"> {!! $daycareRecord->Uac !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacPosition'] }}"> {!! $daycareRecord->UacPosition !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacDay'] }}"> {!! $daycareRecord->UacDay !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['UacComplication'] }}"> {!! $daycareRecord->UacComplication !!} </td>
                        <td class="flex-filter flex-width-small {{ $daycareHeadclass['Pac'] }}"> {!! $daycareRecord->Pac !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PacSite'] }}"> {!! $daycareRecord->PacSite !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['PacDay'] }}"> {!! $daycareRecord->PacDay !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['PacComplication'] }}"> {!! $daycareRecord->PacComplication !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['SkinICD'] }}"> {!! isset($daycareRecord->SkinICD) ? $daycareRecord->SkinICD : '' !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['Skin'] }}"> {!! $daycareRecord->Skin !!} </td>
                        <td class="flex-filter flex-width-xmedium {{ $daycareHeadclass['RopICD'] }}"> {!! isset($daycareRecord->RopICD) ? $daycareRecord->RopICD : '' !!} </td>
                        <td class="flex-filter flex-width-medium {{ $daycareHeadclass['Rop'] }}"> {!! $daycareRecord->Rop !!} </td>
                        <td class="flex-filter flex-width-xlarge {{ $daycareHeadclass['Plan'] }}"> {!! $daycareRecord->Plan !!} </td>
                        <td class="flex-filter {{ $daycareHeadclass['Notes'] }}"> {!! $daycareRecord->Notes !!} </td>
                    </tr>
@endforeach

 
         